#! /bin/bash
#PBS -l walltime=40:00:00
#PBS -l select=1:ncpus=10:mem=30gb
module load anaconda3/personal
module load cuda/11.4.2
source activate py311
echo "Running"
i=0
export LOAD=true
while [ $i -ne 1000 ]
do
        i=$(($i+1))
        python $HOME/FYPDeepDeconstructedLearning/main.py
        echo $i
        export LOAD=true
done
mkdir $WORK/$PBS_JOBID
cp * $WORK/$PBS_JOBID


### ##PBS -l select=1:ncpus=11:mem=30gb
#PBS -l select=1:ncpus=10:mem=30gb:ngpus=1:gpu_type=RTX6000
