#! /bin/bash
#PBS -l walltime=40:00:00
#PBS -l select=1:ncpus=11:mem=30gb
module load anaconda3/personal
source activate py311
export LOAD=false
echo "Running"
i=0
while [ $i -ne 1000 ]
do
        i=$(($i+1))
        python $HOME/FYPDeepDeconstructedLearning/main3.py
        echo $i
        export LOAD=true
done
mkdir $WORK/$PBS_JOBID
cp * $WORK/$PBS_JOBID


### #PBS -l select=1:ncpus=4:mem=8gb:ngpus=1:gpu_type=RTX6000
