#! /bin/bash
#PBS -l walltime=40:00:00
#PBS -l select=1:ncpus=20:mem=50gb
module load anaconda3/personal
source activate py311
export first_run=True
echo "Running"
i=0
export LOAD=false
while [ $i -ne 1000 ]
do
        i=$(($i+1))
        python $HOME/FYPDeepDeconstructedLearning/main.py
        echo $i
        export LOAD=true
done
mkdir $WORK/$PBS_JOBID
cp * $WORK/$PBS_JOBID


### ##PBS -l select=1:ncpus=11:mem=30gb
